# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 604d5106f155afbef71cab42937062fa6db36d3d79284957f06de5f0a9053e669bf2bf2202e0bc6c9adf408a23703d3af49a4f64aee0ebd346d1946bdbe12dd3

test:
  secret_key_base: 46adffc8634e7d4b21c59d442126fe7a9ad0187fb93673aa7ff94de367798f8c257f03602e363b459f46e020ca3f082255ef5fb63b79b2e36d69b68d3f0f5e15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
